export type Definition = {
  name: string;
  display: boolean; // ユーザーが入力するか
  const?: string | number; // ユーザーが入力しない場合の固定値が存在するとき設定
  type?: 'input' | 'select'; // inputタグかプルダウンか
  placeholder?: string;
  options?: { value: string; text: string }[]; // プルダウンのoption
};

export type Definitions = Definition[];

export const pharmacyColumnsDefinition: Definitions = [
  { name: 'バージョン情報', display: false, const: 'VER010501' },
  { name: '送信日時', display: false, const: '20220101000000' },
  { name: '備考', display: false },
  { name: '送信端末識別情報', display: false },
  { name: '都道府県番号', display: false },
  { name: '点数表', display: false, const: 4 },
  { name: '薬局コード', display: true, type: 'input' },
  { name: '薬局名', display: true, type: 'input', placeholder: 'とある薬局' },
  { name: '薬局郵便番号', display: true, type: 'input' },
  { name: '薬局所在地', display: true, type: 'input' },
  { name: '薬局電話番号', display: true, type: 'input' },
  { name: '旧ファイル名', display: false },
];

export const patientColumnsDefinition: Definitions = [
  { name: '識別子', display: false, const: 1 },
  { name: '患者コード', display: true, type: 'input' },
  { name: '患者カナ氏名', display: true, type: 'input' },
  { name: '患者漢字氏名', display: true, type: 'input' },
  {
    name: '性別',
    display: true,
    type: 'select',
    options: [
      { value: 'male', text: '男' },
      { value: 'female', text: '女' },
    ],
  },
  { name: '生年月日', display: false },
  { name: '郵便番号', display: false },
  { name: '住所', display: false },
  { name: '自宅電話番号', display: false },
  { name: '勤務先電話番号', display: false },
  { name: '緊急連絡先', display: false },
  { name: 'メールアドレス', display: false },
  { name: '一部負担金区分', display: false },
  { name: '保険種別', display: false },
  { name: '保険者番号', display: false },
  { name: '被保険者番号取得日', display: false },
  { name: '被保険者証記号', display: false },
  { name: '被保険者証番号', display: false },
  { name: '被保険者／被扶養者', display: false },
  { name: '患者負担率', display: false },
  { name: '保険給付率', display: false },
  { name: '職務上の事由', display: false },
  { name: '老人保険市町村番号', display: false },
  { name: '老人保険受給者番号', display: false },
  { name: '老人保険市町村番号取得日', display: false },
  { name: '第一公費負担者番号', display: false },
  { name: '第一公費受給者番号', display: false },
  { name: '第一公費負担者番号取得日', display: false },
  { name: '第二公費負担者番号', display: false },
  { name: '第二公費受給者番号', display: false },
  { name: '第二公費負担者番号取得日', display: false },
  { name: '第三公費負担者番号', display: false },
  { name: '第三公費受給者番号', display: false },
  { name: '第三公費負担者番号取得日', display: false },
  { name: '特殊公費負担者番号', display: false },
  { name: '特殊公費受給者番号', display: false },
  { name: '特殊公費負担者番号取得日', display: false },
  { name: '１包化指示', display: false },
  { name: '粉砕指示', display: false },
  { name: '注意薬あり', display: false },
  { name: '相互作用チェック', display: false },
  { name: '相互作用チェック（他薬局）', display: false },
  { name: '投与量オーバー（向）', display: false },
  { name: '投与量オーバー（他）', display: false },
  { name: '長禁', display: false },
  { name: '重複投与', display: false },
  { name: '重複投与（他薬局）', display: false },
  { name: '保険種別コード', display: false },
];

const prescription_column_names = [
  '識別子',
  '処方箋番号',
  '受付番号',
  '更新区分',
  '処方箋交付年月日',
  '使用期限年月日',
  '受付年月日',
  '調剤年月日',
  '妊娠授乳区分',
  '強制監査指示フラグ',
  '医療機関コード種別',
  '医療機関コード',
  '医療機関レセプトコード',
  '医療機関都道府県コード',
  '医療機関名',
  '医療機関郵便番号',
  '医療機関所在地',
  '医療機関電話番号',
  '診療科コード',
  '診療科名',
  '病棟コード',
  '病棟名',
  '医師コード',
  '医師カナ氏名',
  '医師漢字氏名',
  '薬剤師コード',
  '薬剤師名',
  '医師同意変更内容',
  '医師疑義回答内容',
  '麻薬施用者免許番号',
  '麻薬施用患者住所',
  '麻薬施用患者電話番号',
  '処方箋コメント',
  '処方箋情報部予備',
  '薬袋発行フラグ',
  '薬情発行フラグ',
  '服薬手帳発行フラグ',
  '領収書発行フラグ',
  '帳票A発行フラグ',
  '帳票B発行フラグ',
  '帳票C発行フラグ',
  '明細書発行フラグ',
];

const administration_column_names = [
  '識別子',
  'RP番号',
  '用法コード１',
  '用法名１',
  '用法コード２',
  '用法名２',
  '用法コード３',
  '用法名３',
  'RP区分',
  '日回区分',
  '日回数',
  '服用回数',
  '服用開始日',
  '薬品明細数',
  '１包化RP区分',
  '粉砕RP区分',
  '用法コメント１',
  '用法部予備',
  '用法コメント２',
  '用法コメント３',
  '用法コメント４',
  '用法コメント５',
];

const medicine_column_names = [
  '識別子',
  '薬品番号',
  'RP番号',
  '情報区分',
  'YJコード',
  'レセ電算コード',
  'HOTコード',
  '明細コード',
  '薬品名',
  '薬品一般名',
  '不均等分割服用量（起床時）',
  '不均等分割服用量（朝）',
  '不均等分割服用量（昼）',
  '不均等分割服用量（夕）',
  '不均等分割服用量（寝る前）',
  '不均等分割服用量（予備）',
  '服用量',
  '力価フラグ',
  '服用単位',
  '１包化区分',
  '粉砕区分',
  '画像区分',
  '別包区分',
  '表示区分',
  '薬価',
  '棚番号',
  'ロット番号',
  '薬品コメント１',
  '後発品変更前薬品YJコード',
  '後発品変更前薬品レセ電算コード',
  '後発品変更前薬品HOTコード',
  '後発品変更前薬品名',
  '混合区分',
  '後発品変更前薬品服用量',
  '後発品変更前薬品服用単位',
  '１回服用量',
  '薬品コメント２',
  '薬品コメント３',
  '薬品コメント４',
  '薬品コメント５',
  '一般名処方フラグ',
];

const prescription_book_column_names = [
  '識別子',
  '薬剤料の合計',
  '調剤料の合計',
  '指導管理料の合計',
  '特定保険医療材料料',
  '保険請求点数',
  '基本加算',
  '調剤基本料',
  '加算の合計',
  '薬歴',
  'その他の指導料',
  '加算等',
  '合計点数',
  '一部負担金',
  '容器金額',
  'その他金額',
  '前回迄未収金',
  '今回請求額',
  '合計請求額',
  '今回入金額',
  '未収金',
];

const prescription_book_detail_column_names = [
  '識別子',
  'RP番号',
  '調剤料',
  '薬剤料',
  '数量',
  '小計',
  '薬剤加算',
  '合計',
  '薬剤加算コード01',
  '薬剤加算の内容01',
  '薬剤加算コード02',
  '薬剤加算の内容02',
  '薬剤加算コード03',
  '薬剤加算の内容03',
  '薬剤加算コード04',
  '薬剤加算の内容04',
  '薬剤加算コード05',
  '薬剤加算の内容05',
  '薬剤加算コード06',
  '薬剤加算の内容06',
  '薬剤加算コード07',
  '薬剤加算の内容07',
  '薬剤加算コード08',
  '薬剤加算の内容08',
  '薬剤加算コード09',
  '薬剤加算の内容09',
  '薬剤加算コード10',
  '薬剤加算の内容10',
];

const addtional_columns_names = [
  '識別子',
  '加算番号',
  '算定コード',
  '算定名称',
  '回数',
  '点数',
];
